site_name: NH Switch Guide
theme: slate
copyright: Copyright &copy; 2019 <a href="https://discord.gg/C29hYvh" target="_blank">Nintendo Homebrew</a>, Maintained by the <a href="/switch-guide/about">NH Discord Server</a>.
site_description: Switch CFW Guide.
site_author: NH Discord Server.

nav:
    - Home: index.md
    - User Guide:
        - 'Getting Started': 'user_guide/getting_started.md'
        - 'RCM': 'user_guide/rcm.md'        
        - 'Partitioning the SD': 'user_guide/emummc/partitioning_sd.md'    
        - 'SD preparations': 'user_guide/emummc/sd_preparation.md'
        - 'Entering RCM': 'user_guide/emummc/entering_rcm.md'
        - 'Sending a payload': 'user_guide/emummc/sending_payload.md'
        - 'Making the emuMMC': 'user_guide/emummc/making_emummc.md'
        - 'Launching CFW': 'user_guide/emummc/launching_cfw.md'
    - Extras:
        - 'Blocking Updates': 'extras/blocking_updates.md'
        - 'Restoring a NAND Backup': 'extras/nandrestore.md'
        - 'AutoRCM': 'extras/autorcm.md'
        - 'Dumping Title Keys': 'extras/dumping_title_keys.md'
        - 'Theming': 'extras/theming.md'
        - 'Save Management': 'extras/save_management.md'
        - 'Game Modding': 'extras/game_modding.md'       
        - 'Linux injection without root': 'extras/adding_udev.md'
        - 'Showing File Name Extensions (Windows)': 'extras/showing_file_extensions.md'
        - 'Alternate Boot Setups': 'extras/alternate_bootsetups.md'
        - 'Glossary': 'extras/glossary.md'
        - 'RCM Payload Injectors Information': 'extras/rcm_injectors.md'
    - FAQ: faq.md
    - About: about.md
    
markdown_extensions:
    - admonition
    - fontawesome_markdown

extra_css:
    - css/custom.css
