site_name: NH Switch Guide
theme: slate
copyright: Copyright &copy; 2019 <a href="https://discord.gg/C29hYvh" target="_blank">Nintendo Homebrew</a>, Maintained by the <a href="/switch-guide/about">NH Discord Server</a>.
site_description: Switch CFW Guide.
site_author: NH Discord Server.

nav:
    - Home: index.md
    - User Guide:
        - 'Getting Started': 'user_guide/getting_started.md'
        - 'SD Preparation': 'user_guide/sd_preparation.md'        
        - 'Entering RCM': 'user_guide/entering_rcm.md'    
        - 'Sending a Payload': 'user_guide/sending_payload.md'
        - 'Making a NAND Backup': 'user_guide/making_a_nand_backup.md'
        - 'Launching CFW': 'user_guide/launching_cfw.md'
    - Extras:
        - 'Blocking Updates': 'extras/blocking_updates.md'
        - 'Manual RCM Testing': 'extras/rcm_test.md'
        - 'Backup Keys': 'extras/backup_keys.md'
        - 'Theming': 'extras/theming.md'
        - 'Save Management': 'extras/save_management.md'
        - 'Game Modding': 'extras/game_modding.md'  
        - 'Giving Homebrew More RAM': 'extras/himem_homebrew.md'      
        - 'Linux injection without root': 'extras/adding_udev.md'
    - FAQ: faq.md
    - About: about.md
    
markdown_extensions:
    - admonition
    - fontawesome_markdown

extra_css:
    - css/custom.css
